kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: quay.io/quarkus/ubi-quarkus-native-s2i:19.3.1-java11
    commands:
      - echo hello
      - echo world
      - ./mvnw clean package -Dquarkus.kubernetes.deploy=true
