kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: adoptopenjdk/openjdk11
    user: 0
    commands:
      - chmod +rwx ./mvnw
      - ./mvnw mvn package -Dquarkus.package.type=fast-jar 
  - name: docker
    image: plugins/docker
    settings:
      repo: modeseven/rfds
      dockerfile: src/main/docker/Dockerfile.fast-jar
      tags:
       - '0.1'
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
