kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: adoptopenjdk/openjdk11
    user: 0
    commands:
      - echo hello
      - echo world
      - ./mvnw clean package -Dquarkus.kubernetes.deploy=true
